version: '3.8'
services:
  db:
    image: postgis/postgis
    restart: always
    tty: true
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-c", "log_statement=all"]
    container_name: database

  app:
    build: .
    tty: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    container_name: nodeapp

volumes:
  pgdata:
